name: GitHub Profile Summary Cards

on:
  schedule: # Runs every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch: # Allow manual runs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: vn7n24fzkq/github-profile-summary-cards@release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
